name: dicoding_flutter_story_app
description:
  Projects from dicoding.com as a practice in advanced navigation, use of media
  (audio, images, and video), and use of maps such as Google Map.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Dart utils
  get_it: ^7.6.0
  http: ^0.13.6

  # Flutter utils
  cached_network_image: ^3.2.3
  core:
    git:
      url: https://github.com/KeidsID/flutter_app_core_package.git
  go_router: ^7.0.0
  package_info_plus: ^4.0.1
  provider: ^6.0.5
  shared_preferences: ^2.1.0

  # Media
  camera: ^0.10.5
  camera_windows: ^0.2.1+6
  image_picker: ^0.8.7+5
  image_picker_windows: ^0.1.0+6

  # App utils generator
  icons_launcher: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
